### ISSUE TITLE
Allow multiple accounts to be linked to a Dojo

### ISSUE THREAD

**Issue by sandervdo** [CoderDojoNederland/Website#70]
Having had a look at the system, I have to following suggestion;

In some cases it might be really useful that other users than the Champion can create dojo's on the website. Therefore I suggest splitting the Dojo table into Dojo and Users. This way we can hook multiple users to a single Dojo. We can specify one _main_ account per dojo, this account would be able to change the Dojo details. Others will only be able to create dojo's/events.

If we want to implement this we need to alter the current database structure, implement some kind of role/access system and implement different views for both Champions and non-champions.

Thoughts? :grinning:

**Comment by ChristianVermeulen** [comment]
Sounds cool to me! Allthough I think we would make it more complicated then necessary. This also brings us awefully close to the structure of the Zen platform.

Since everything is pretty tied up with eventbrite I think it's no big deal to share the dojo login amongst the mentors who should be able to add dojo's.

Then again, if you have the time to spare, feel free to make a proof of concept :). As for users and usage rights, we use [FOS UserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle); it has most of that already built in!

Maybe @Tmw has some 2 cents?
